config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcomes#index'
  resources :welcomes, only: [:index]

  # Devise
  devise_for :users

  # Hiring Quiz
  resources :assessments, except: [:new]
  resources :hiring_results, only: [:index]
  get '/quiz_intro', to: 'assessments#intro'
  get '/hiring_quiz', to: 'assessments#new'



  # D & I assessments (original)
  resources :diversity_results, only: [:index]
  resources :diversities, except: [:new]
  # get '/diversity_intro', to: 'diversities#intro'
  get '/diversity_assessment', to: 'diversities#new'

  ## D & I assessments (updated) ##
  resources :respondents, only: [:new, :create] do
    resources :responses
  end
  get '/diversity_intro', to: 'respondents#new'
end

app/models/assessment.rb
class Assessment < ApplicationRecord
    validates :remoteOneValue, presence: { message: "Question 1 was left unanswered." }

    validates :remoteTwoValue, presence: { message: "Question 2 was left unanswered." }

    validates :remoteThreeValue, presence: { message: "Question 3 was left unanswered." }

    validates :remoteFourValue, presence: { message: "Question 4 was left unanswered." }

    validates :remoteFiveValue, presence: { message: "Question 5 was left unanswered." }

    validates :strategyOneValue, presence: { message: "Question 6 was left unanswered." }

    validates :strategyTwoValue, presence: { message: "Question 7 was left unanswered." }

    validates :strategyThreeValue, presence: { message: "Question 8 was left unanswered." }

    validates :strategyFourValue, presence: { message: "Question 9 was left unanswered." }

    validates :strategyFiveValue, presence: { message: "Question 10 was left unanswered." }

    validates :strategySixValue, presence: { message: "Question 11 was left unanswered." }

    validates :name, presence: { message: "Please enter your name." }

    validates :email, presence: { message: "Please enter your email." }

end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
    @assessments = Assessment.find(params[:id])

    @remoteScore = @assessments.remoteOneValue + @assessments.remoteTwoValue + @assessments.remoteThreeValue + @assessments.remoteFourValue + @assessments.remoteFiveValue;

    @strategyScore = @assessments.strategyOneValue + @assessments.strategyTwoValue + @assessments.strategyThreeValue + @assessments.strategyFourValue + @assessments.strategyFiveValue + @assessments.strategySixValue;

    @totalScore = @assessments.remoteOneValue + @assessments.remoteTwoValue + @assessments.remoteThreeValue + @assessments.remoteFourValue + @assessments.remoteFiveValue + @assessments.strategyOneValue + @assessments.strategyTwoValue + @assessments.strategyThreeValue + @assessments.strategyFourValue + @assessments.strategyFiveValue + @assessments.strategySixValue;
  end

  # Quiz Intro

  def intro
  end  

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: 'Assessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.fetch(:assessment).permit(:remoteOneValue,:remoteTwoValue,:remoteThreeValue, :remoteFourValue, :remoteFiveValue, :strategyOneValue, :strategyTwoValue, :strategyThreeValue, :strategyFourValue, :strategyFiveValue, :strategySixValue, :name, :email)
    end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<script>
$(document).ready(function(){
  $("#question2").hide();
  $("#question3").hide();
  $("#question4").hide();
  $("#question5").hide();
  $("#question6").hide();
  $("#question7").hide();
  $("#question8").hide();
  $("#question9").hide();
  $("#question10").hide();
  $("#question11").hide();
  $("#button").hide();
  $("#email").hide();


  $('.question1').click(function(){
    $('#question1').hide();
    $('#question2').show();
  });

  $('.question2').click(function(){
    $('#question2').hide();
    $('#question3').show();
  });

  $('.question3').click(function(){
    $('#question3').hide();
    $('#question4').show();
  });

  $('.question4').click(function(){
    $('#question4').hide();
    $('#question5').show();
  });

  $('.question5').click(function(){
    $('#question5').hide();
    $('#question6').show();
  });

  $('.question6').click(function(){
    $('#question6').hide();
    $('#question7').show();
  });

  $('.question7').click(function(){
    $('#question7').hide();
    $('#question8').show();
  });

  $('.question8').click(function(){
    $('#question8').hide();
    $('#question9').show();
  });

  $('.question9').click(function(){
    $('#question9').hide();
    $('#question10').show();
  });

  $('.question10').click(function(){
    $('#question10').hide();
    $('#question11').show();
  });

  $('.question11').click(function(){
    $('#question11').hide();
    $('#email').show();
  });

  $('.bquestion1').click(function(){
    $('#question2').hide();
    $('#question1').show();
  });

  $('.bquestion2').click(function(){
    $('#question3').hide();
    $('#question2').show();
  });

  $('.bquestion3').click(function(){
    $('#question4').hide();
    $('#question3').show();
  });

  $('.bquestion4').click(function(){
    $('#question5').hide();
    $('#question4').show();
  });

  $('.bquestion5').click(function(){
    $('#question6').hide();
    $('#question5').show();
  });

  $('.bquestion6').click(function(){
    $('#question7').hide();
    $('#question6').show();
  });

  $('.bquestion7').click(function(){
    $('#question8').hide();
    $('#question7').show();
  });

  $('.bquestion8').click(function(){
    $('#question9').hide();
    $('#question8').show();
  });

  $('.bquestion9').click(function(){
    $('#question10').hide();
    $('#question9').show();
  });

  $('.bquestion10').click(function(){
    $('#question11').hide();
    $('#question10').show();
  });

});
</script>


<%= form_for [@assessment], url: assessments_path, html: { multipart: true } do |f| %>

<!-- 11 Hiring Quiz-->
  <div id="question1" class="well">
    <div class="quiz_box">
      <p class="text">1. My friends would say I enjoy learning new technologies.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteOneValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteOneValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteOneValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteOneValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary question1">Next</a>
    </div>
  </div>

  <div id="question2" class="well">
    <div class="quiz_box">
      <p class="text">2. When given the choice, I prefer to be given a task list to run with.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteTwoValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteTwoValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteTwoValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteTwoValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion1">Back</a>
      <a class="btn btn-primary question2">Next</a>
    </div>
  </div>

  <div id="question3" class="well">
    <div class="quiz_box">
      <p class="text">3. I enjoy solving problems.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteThreeValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteThreeValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteThreeValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteThreeValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion2">Back</a>
      <a class="btn btn-primary question3">Next</a>
    </div>
  </div>

  <div id="question4" class="well">
    <div class="quiz_box">
      <p class="text">4. I work best in a social environment.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFourValue, 0 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFourValue, 1 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFourValue, 2 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFourValue, 4 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion3">Back</a>
      <a class="btn btn-primary question4">Next</a>
    </div>
  </div>

  <div id="question5" class="well">
    <div class="quiz_box">
      <p class="text">5. When I start my day, I respond to all emails before reviewing priorities for the day.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFiveValue, 0 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFiveValue, 1 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFiveValue, 2 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :remoteFiveValue, 4 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion4">Back</a>
      <a class="btn btn-primary question5">Next</a>
    </div>
  </div>

  <div id="question6" class="well">
    <div class="quiz_box">
      <p class="text">6. I like to multitask on conference calls.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyOneValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyOneValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyOneValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyOneValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion5">Back</a>
      <a class="btn btn-primary question6">Next</a>
    </div>
  </div>

  <div id="question7" class="well">
    <div class="quiz_box">
      <p class="text">7. I'm willing to try a new approach or process even if it might not work.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyTwoValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyTwoValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyTwoValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyTwoValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion6">Back</a>
      <a class="btn btn-primary question7">Next</a>
    </div>
  </div>

  <div id="question8" class="well">
    <div class="quiz_box">
      <p class="text">8. If the internet were to go down at work and I had an important assignment to finish, I’d stay on the phone with the internet provider as long as it took and let my boss know my work might be late.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyThreeValue, 0 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyThreeValue, 1 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyThreeValue, 2 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyThreeValue, 4 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion7">Back</a>
      <a class="btn btn-primary question8">Next</a>
    </div>
  </div>

  <div id="question9" class="well">
    <div class="quiz_box">
      <p class="text">9. I’m okay with not being an expert in everything I do.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFourValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFourValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFourValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFourValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion8">Back</a>
      <a class="btn btn-primary question9">Next</a>
    </div>
  </div>

  <div id="question10" class="well">
    <div class="quiz_box">
      <p class="text">10. Giving presentations isn’t my thing.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFiveValue, 0 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFiveValue, 1 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFiveValue, 2 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategyFiveValue, 4 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion9">Back</a>
      <a class="btn btn-primary question10">Next</a>
    </div>
  </div>

  <div id="question11" class="well">
    <div class="quiz_box">
      <p class="text">11. I already or would like to provide ways to give back to my community.</p>
      <div class="radio">
        <label>
          <%= f.radio_button :strategySixValue, 4 %>
          <span>Strongly Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategySixValue, 2 %>
          <span>Moderately Agree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategySixValue, 1 %>
          <span>Moderately Disagree</span>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :strategySixValue, 0 %>
          <span>Strongly Disagree</span>
        </label>
      </div>
      <a class="btn btn-primary bquestion10">Back</a>
      <a class="btn btn-primary question11">Next</a>
    </div>
  </div>

  <div id="email" class="well">
    <div class="quiz_user_info">
      <p class="text">Please tell us a little bit about yourself to see your results.</p>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "First & Last Name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
      </div>
      <%= f.submit 'See Results', :class => 'btn btn-primary btn-submit' %>
      </div>
    </div>
  </div>

<% end %>

app/views/assessments/edit.html.erb
<h1>Editing Assessment</h1>

<%= render 'form2', assessment: @assessment %>

<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', assessments_path %>

app/views/assessments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assessments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= link_to 'Show', assessment %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assessment', new_assessment_path %>

app/views/assessments/intro.html.erb
<div class="container quiz_intro">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>Artemis Quiz</h1>
      <div class="well">
        <p>We're excited about your interest in Artemis. We are a next generation strategy firm and are always looking for great people to join our growing team. We believe in providing a transparent hiring process and this quiz will provide us with some helpful information about you as well as you'll get a sense of what the day-to-day at Artemis is like. Please continue to the quiz to see if remote strategy work is right for you. </p>
        <a href="/hiring_quiz">
          <span>Take our quiz</span>
          <i class="fa fa-arrow-circle-right fa-4x" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/assessments/new.html.erb
<div class="container quiz_body">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1 style="text-align:center;">Is Artemis right for you?</h1>
      <%= render 'form', assessment: @assessment %>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% if @assessment.errors.any? %>
          <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% @assessment.errors.each do | name, message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/assessments/show.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 quiz_result">
      <div class="quiz_result_head">
        <h3>Thank you for taking our quiz. This gives us a sense of who you are and serves as a tool for you to evaluate if strategy consulting and working in a remote environment is right for you.</h3>
      </div>

      <div class="quiz_result_body">
        <h2>Your Result</h2>
      </div>
    </div>
  </div>
</div> -->

<% if @remoteScore >= 14 && @strategyScore >= 16 %>
  <div class="response-box1">
    <div class="container">
      <h2 class="well">Your Results</h2>
      <div class="container">
        <h4>Thank you for taking our quiz. This gives us a sense of who you are and serves as a tool for you to evaluate if strategy consulting and working in a remote environment is right for you.</h4>
        <br>
        <div class="panel panel-info">
          <div class="panel-heading">
          <h4 class="panel-title">Artemis Connection Quiz</h4>
          </div>

          <div class="row panel-body" >
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top:40px;">
              <div class="w3-border">
                <div class="w3-grey" style="height:24px; width:100%; text-align:center; background-color:#758DA2!important">100%</div>
              </div>
            </div>

            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-top:20px;">
              We think you're going to love working remotely! You seem to have all the right qualities it takes to be a successful remote worker as well as a collaborator with us.
              <br>
              <br>
            </div>
            <a href="http://www.artemisconnection.com/application" class="btn btn-primary" style="margin-left:10px">Apply</a>
          </div>
        </div>
      </div>
    </div>
  </div>

<% elsif @remoteScore >= 10 && @strategyScore >= 14 %>
  <div class="container">
    <h2 class="well">Your Results</h2>
    <div class="container">
      <h4>Thank you for taking our quiz. This gives us a sense of who you are and serves as a tool for you to evaluate if strategy consulting and working in a remote environment is right for you.</h4>
      <br>
      <div class="panel panel-info">
        <div class="panel-heading">
        <h4 class="panel-title">Artemis Connection Quiz</h4>
        </div>

        <div class="row panel-body">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top:40px;">
            <div class="w3-border">
              <div class="w3-grey" style="height:24px; width:80%; text-align:center; background-color:#758DA2!important">80%</div>
            </div>
          </div>

          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-top:20px;">
            We think you would be a strong remote worker but don't quite have the collaborator experience. Since you are so close to being a good fit, why not apply and we will see if we can work with you.
            <br>
          </div>
          <a href="http://www.artemisconnection.com/application" class="btn btn-primary" style="margin-left:10px">Apply</a>
        </div>
      </div>
    </div>
  </div>
<% elsif @remoteScore < 10 || @strategyScore < 12 %>
  <div class="container">
    <h2 class="well">Your Results</h2>
    <div class="container">
      <h4>Thank you for taking our quiz. This gives us a sense of who you are and serves as a tool for you to evaluate if strategy consulting and working in a remote environment is right for you.</h4>
      <br>
      <div class="panel panel-info">
        <div class="panel-heading">
        <h4 class="panel-title">Artemis Connection Quiz</h4>
        </div>

        <div class="row panel-body">

          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p style="font-size:18px;">Strategy and remote work is not for everyone. We find people that gravitate towards it enjoy problem solving, are open to learning new technologies, self-motivated and are comfortable not working in a social environment.
            </p>
            <h3>We wish you best in your search and recommend you check out the following companies:</h3>

      <h4>Ex-Consultants Agency: <a href="https://www.exconsultantsagency.com/">https://www.exconsultantsagency.com/</a></h4>
      <h4>SpareHire: <a href="http://www.sparehire.com">sparehire.com</a></h4>
      <h4>Hillgate: <a href="https://www.hillgateconnect.com/">https://www.hillgateconnect.com/</a></h4>
      <h4>AngelList: <a href="https://angel.co/">https://angel.co/</a></h4>
      <h4>Catalant: <a href="https://gocatalant.com/">https://gocatalant.com/</a></h4>
      <h4>Remote.co: <a href="https://remote.co/">https://remote.co/</a></h4>
      <h4>Flexjobs: <a href="https://www.flexjobs.com/">https://www.flexjobs.com/</a></h4>
      <h4>Talent Response: <a href="http://www.talentresponse.com/">http://www.talentresponse.com/</a></h4>
      <h4>Business Talent Group: <a href="https://businesstalentgroup.com">https://businesstalentgroup.com</a></h4>
          </div>
          <a href="http://www.artemisconnection.com/" class="btn btn-primary" style="margin-left:10px">Back To Artemis</a>
        </div>
      </div>
    </div>
  </div>
<% end %>