config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcomes#index'
  resources :welcomes, only: [:index]

  # Devise
  devise_for :users

  # Hiring Quiz
  resources :assessments, except: [:new]
  resources :hiring_results, only: [:index]
  get '/quiz_intro', to: 'assessments#intro'
  get '/hiring_quiz', to: 'assessments#new'



  # D & I assessments (original)
  resources :diversity_results, only: [:index]
  resources :diversities, except: [:new]
  # get '/diversity_intro', to: 'diversities#intro'
  get '/diversity_assessment', to: 'diversities#new'

  ## D & I assessments (updated) ##
  resources :respondents, only: [:new, :create] do
    resources :responses
  end
  get '/diversity_intro', to: 'respondents#new'
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
# section_one
    @section_one = @response.section_one

    total_one = 0
    @section_one.each do |i|
      total_one += i[1].to_i
    end
    @section_one_total = total_one/5

    one = @response.section_one.select{|i| i[1] == "1"}
    @section_one_question_ones = []
    one.each do |i|
      @section_one_question_ones.push(Question.find(i[0]).question_text)
    end

    two = @response.section_one.select{|i| i[1] == "2"}
    @section_one_question_twos = []
    two.each do |i|
      @section_one_question_twos.push(Question.find(i[0]).question_text)
    end


# section_two
    @section_two = @response.section_two

    total_two = 0
    @section_two.each do |i|
      total_two += i[1].to_i
    end
    @section_two_total = total_two/15

    three = @response.section_two.select{|i| i[1] == "1"}
    @section_two_question_ones = []
    three.each do |i|
      @section_two_question_ones.push(Question.find(i[0]).question_text)
    end

    four = @response.section_two.select{|i| i[1] == "2"}
    @section_two_question_twos = []
    four.each do |i|
      @section_two_question_twos.push(Question.find(i[0]).question_text)
    end

# section_three
    @section_three = @response.section_three

    total_three = 0
    @section_three.each do |i|
      total_three += i[1].to_i
    end
    @section_three_total = total_three/6

    five = @response.section_three.select{|i| i[1] == "1"}
    @section_three_question_ones = []
    five.each do |i|
      @section_three_question_ones.push(Question.find(i[0]).question_text)
    end

    six = @response.section_three.select{|i| i[1] == "2"}
    @section_three_question_twos = []
    six.each do |i|
      @section_three_question_twos.push(Question.find(i[0]).question_text)
    end

# section_four
    @section_four = @response.section_four

    total_four = 0
    @section_four.each do |i|
      total_four += i[1].to_i
    end
    @section_four_total = total_four/15

    seven = @response.section_four.select{|i| i[1] == "1"}
    @section_four_question_ones = []
    seven.each do |i|
      @section_four_question_ones.push(Question.find(i[0]).question_text)
    end

    eight = @response.section_four.select{|i| i[1] == "2"}
    @section_four_question_twos = []
    eight.each do |i|
      @section_four_question_twos.push(Question.find(i[0]).question_text)
    end

# section_five
    @section_five = @response.section_five

    total_five = 0
    @section_five.each do |i|
      total_five += i[1].to_i
    end
    @section_five_total = total_five/4

    nine = @response.section_five.select{|i| i[1] == "1"}
    @section_five_question_ones = []
    nine.each do |i|
      @section_five_question_ones.push(Question.find(i[0]).question_text)
    end

    ten = @response.section_five.select{|i| i[1] == "2"}
    @section_five_question_twos = []
    ten.each do |i|
      @section_five_question_twos.push(Question.find(i[0]).question_text)
    end

# section_six
    @section_six = @response.section_six

    total_six = 0
    @section_six.each do |i|
      total_six += i[1].to_i
    end
    @section_six_total = total_six/6

    eleven = @response.section_six.select{|i| i[1] == "1"}
    @section_six_question_ones = []
    eleven.each do |i|
      @section_six_question_ones.push(Question.find(i[0]).question_text)
    end

    twelve = @response.section_six.select{|i| i[1] == "2"}
    @section_six_question_twos = []
    twelve.each do |i|
      @section_six_question_twos.push(Question.find(i[0]).question_text)
    end

# section_seven
    @section_seven = @response.section_seven

    total_seven = 0
    @section_seven.each do |i|
      total_seven += i[1].to_i
    end
    @section_seven_total = total_seven/4

    thirteen = @response.section_seven.select{|i| i[1] == "1"}
    @section_seven_question_ones = []
    thirteen.each do |i|
      @section_seven_question_ones.push(Question.find(i[0]).question_text)
    end

    fourteen = @response.section_seven.select{|i| i[1] == "2"}
    @section_seven_question_twos = []
    fourteen.each do |i|
      @section_seven_question_twos.push(Question.find(i[0]).question_text)
    end


# summary
  to = @response.one_hash
  to.delete! '\\"" {}'
  to.gsub!(/=>/,',')
  split = to.split(",")
  array = eval split.to_s.gsub('"', '')
  groups = array.in_groups_of(2)

  @ones = []
  groups.each do |i|
    @ones.push(Question.find(i[0]).question_text)
  end



    @onesWeight = []
    groups.each do |i|
      @onesWeight.push(Answer.find(i[0]).answer_weight)
    end

    @average = @onesWeight.inject{ |sum, el| sum + el }.to_f / @onesWeight.size

    @section_one = @response.section_one
    total_one = 0
      @section_one.each do |i|
      total_one += i[1].to_i
      end
    @section_one_total = total_one/5

  end

  # GET /responses/new
  def new
    @response = Response.new
    @question = Question.all
    @answers = Answer.all
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @question = Question.all

    @response = Response.new(respondent_id: params["respondent_id"], answer_hash: nil, one_hash: nil, two_hash: nil,three_hash: nil, section_one: nil, section_two: nil, section_three: nil, section_four: nil, section_five: nil, section_six: nil, section_seven: nil)

    i = 1
    answer_hash = Hash.new
    55.times do
      answer_hash[i.to_s] = params["question_id " + i.to_s]
      i += 1
    end


    one_hash = answer_hash.select {|k,v|v == "1"}
    two_hash = answer_hash.select {|k,v|v == "2"}
    three_hash = answer_hash.select {|k,v|v == "3"}

    section_one = Array(answer_hash)[0..4]
    section_two = Array(answer_hash)[5..19]
    section_three = Array(answer_hash)[20..25]
    section_four = Array(answer_hash)[26..40]
    section_five = Array(answer_hash)[41..44]
    section_six = Array(answer_hash)[45..50]
    section_seven = Array(answer_hash)[51..54]

    @response.update(answer_hash: answer_hash, one_hash: one_hash, two_hash: two_hash, three_hash: three_hash, section_one: section_one, section_two: section_two, section_three: section_three, section_four: section_four, section_five: section_five, section_six: section_six, section_seven: section_seven)

    @response.save


    respond_to do |format|
      if @response.save
        format.html { redirect_to respondent_response_url(:id => @response.id), notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end

  end


  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.fetch(:response).permit(:section_number, :user_selection, :user_score, :user_selection, :respondent_id, :answer_hash, :section_one, :section_two, :section_three, :section_four, :section_five, :section_six, :section_seven)
    end

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<script>
$(document).ready(function(){
  event.preventDefault();
  $('.quiz2').hide();
  $('.quiz3').hide();
  $('.quiz4').hide();
  $('.quiz5').hide();
  $('.quiz6').hide();
  $('.quiz7').hide();
  $('.submit').hide();

  $('#quiz2').hide();
  $('#quiz3').hide();
  $('#quiz4').hide();
  $('#quiz5').hide();
  $('#quiz6').hide();
  $('#quiz7').hide();

  $('#heading2').hide();
  $('#heading3').hide();
  $('#heading4').hide();
  $('#heading5').hide();
  $('#heading6').hide();
  $('#heading7').hide();

  $('#quiz1').click(function(){
    $('.quiz1').hide();
    $('.quiz2').show();
    $('#quiz1').hide();
    $('#quiz2').show();
    $('#heading1').hide();
    $('#heading2').show();
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
  });

  $('#quiz2').click(function(){
    $('.quiz2').hide();
    $('.quiz3').show();

    $('#quiz2').hide();
    $('#quiz3').show();
    $('#heading2').hide();
    $('#heading3').show();
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
  });

  $('#quiz3').click(function(){
    $('.quiz3').hide();
    $('.quiz4').show();
    $('#quiz3').hide();
    $('#quiz4').show();
    $('#heading3').hide();
    $('#heading4').show();
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
  });

  $('#quiz4').click(function(){
    $('.quiz4').hide();
    $('.quiz5').show();
    $('#quiz4').hide();
    $('#quiz5').show();
    $('#heading4').hide();
    $('#heading5').show();
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
  });

  $('#quiz5').click(function(){
    $('.quiz5').hide();
    $('.quiz6').show();
    $('#quiz5').hide();
    $('#quiz6').show();
    $('#heading5').hide();
    $('#heading6').show();
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
  });

  $('#quiz6').click(function(){
    $('.quiz6').hide();
    $('.quiz7').show();
    $('#quiz6').hide();
    $('#quiz7').show();
    $('#heading6').hide();
    $('#heading7').show();
    $('.submit').show();
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
  });

});
</script>

<div id="description">
  <div class="container">
    <p id="heading">Diversity &amp; Inclusion Assessment</p>
    <p id="paragraph">
      This tool is meant to enable organizations to benchmark their current diversity and inclusion activities and provide guidance in identifying areas to drive change. Companies that score high demonstrate they are performing at levels considered to be industry best practices while companies that score low demonstrate they have some work to do.
    </p>
  </div>
</div>

<div class="spacer" style="padding:10px;"></div>

<div class="container">
  <%= form_for @response, url: respondent_responses_path, html: { multipart: true } do |f| %>

    <% if @response.errors.any? %>
      <div id="error_explanation">
        <h2> An error prohibited this response from being saved:</h2>

        <ul>
        <% @response.errors.each do |name, message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<div id="heading1">
  <h3 id="heading1">Commitment and Strategy</h3>
    <hr>
</div>
<div id="heading2">
  <h3 id="heading2">Talent Management</h3>
    <hr>
</div>

<div id="heading3">
  <h3 id="heading3">Business Processes</h3>
    <hr>
</div>

<div id="heading4">
  <h3 id="heading4">Culture</h3>
    <hr>
</div>

<div id="heading5">
  <h3 id="heading5" >Community Involvement</h3>
    <hr>
</div>

<div id="heading6">
  <h3 id="heading6">Communication</h3>
    <hr>
</div>

<div id="heading7">
  <h3 id="heading7">Measurement and Evaluation</h3>
    <hr>
</div>


<% @question.each do |question| %>
<% if question.section_number == 1 %>
  <div class="quiz1">
        <div class="row">
          <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <div class="form-group text">
            <%= question.question_text %>
            </div>
          </div>
          <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
            <div class="line"></div>
          </div>

          <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <% question.answers.each do |answer| %>
            <% if answer.answer_weight == 1 %>
              <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
              <% else %>
              <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
              <% end %>
            <% end %>

          </div>
        </div>
      <hr>
    </div>
  <% if question.id == 5 %>
    <a id="quiz1" class="btn btn-primary" style="margin-bottom:20px;">Next</a>
  <% end %>

<% elsif question.section_number == 2 %>
  <div class="quiz2">
    <div class="row">
      <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
        <div class="form-group text">
        <%= question.question_text %>
        </div>
      </div>
      <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
        <div class="line"></div>
      </div>

      <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
        <% question.answers.each do |answer| %>
        <% if answer.answer_weight == 1 %>
        <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
          <% else %>
          <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
          <% end %>
        <% end %>
      </div>
    </div>
    <hr>
  </div>
  <% if question.id == 20  %>
    <a id="quiz2" class="btn btn-primary" style="margin-bottom:20px;">Next</a>
  <% end %>

<% elsif question.section_number == 3 %>
  <div class="quiz3">
      <div class="row">
        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <div class="form-group text">
          <%= question.question_text %>
          </div>
        </div>
        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
          <div class="line"></div>
        </div>

        <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <% question.answers.each do |answer| %>
          <% if answer.answer_weight == 1 %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
          <% else %>
          <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
          <% end %>
          <% end %>
        </div>
      </div>
    <hr>
  </div>
  <% if question.id == 26  %>
    <a id="quiz3" class="btn btn-primary" style="margin-bottom:20px;">Next</a>
  <% end %>


  <% elsif question.section_number == 4 %>
    <div class="quiz4">
      <div class="row">
        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <div class="form-group text">
          <%= question.question_text %>
          </div>
        </div>
        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
          <div class="line"></div>
        </div>

        <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <% question.answers.each do |answer| %>
          <% if answer.answer_weight == 5 %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
          <% else %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
            <% end %>
          <% end %>
        </div>
      </div>
      <hr>
    </div>

    <% if question.id == 41  %>
      <a id="quiz4" class="btn btn-primary" style="margin-bottom:20px;">Next</a>
    <% end %>

  <% elsif question.section_number == 5 %>
    <div class="quiz5">
      <div class="row">
        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <div class="form-group text">
          <%= question.question_text %>
          </div>
        </div>
        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
          <div class="line"></div>
        </div>

        <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <% question.answers.each do |answer| %>
          <% if answer.answer_weight == 1 %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
          <% else %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
            <% end %>
          <% end %>
        </div>
      </div>
      <hr>
    </div>

    <% if question.id == 45  %>
      <a id="quiz5" class="btn btn-primary" style="margin-bottom:20px;">Next</a>
    <% end %>

  <% elsif question.section_number == 6 %>
    <div class="quiz6">
      <div class="row">
        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <div class="form-group text">
          <%= question.question_text %>
          </div>
        </div>
        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
          <div class="line"></div>
        </div>

        <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <% question.answers.each do |answer| %>
          <% if answer.answer_weight == 1 %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
          <% else %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
          <% end %>
          <% end %>
        </div>
      </div>
      <hr>
    </div>

    <% if question.id == 51  %>
      <a id="quiz6" class="btn btn-primary" style="margin-bottom:20px;">Next</a>
    <% end %>

  <% elsif question.section_number == 7 %>
    <div class="quiz7">
      <div class="row">
        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <div class="form-group text">
          <%= question.question_text %>
          </div>
        </div>
        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
          <div class="line"></div>
        </div>

        <div class="radio col-xl-5 col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <% question.answers.each do |answer| %>
          <% if answer.answer_weight == 1 %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight],:checked => true ) %><%= answer.answer_text %> <br>
          <% else %>
            <%= radio_button_tag([:question_id,question.id], [answer.answer_weight]) %> <%= answer.answer_text %> <br>
          <% end %>
          <% end %>
        </div>
      </div>
      <hr>
    </div>

    <% if question.id == 55  %>
      <%= f.submit 'Submit', :class => 'btn btn-primary submit', :style => "margin-bottom:20px;" %>
    <% end %>

  <% end %>

  <% end %>
</div>

    <% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/responses/new.html.erb
<div class="hand_image"></div>
<%= render 'form' %>