config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcomes#index'
  resources :welcomes, only: [:index]

  # Devise
  devise_for :users

  # Hiring Quiz
  resources :assessments, except: [:new]
  resources :hiring_results, only: [:index]
  get '/quiz_intro', to: 'assessments#intro'
  get '/hiring_quiz', to: 'assessments#new'



  # D & I assessments (original)
  resources :diversity_results, only: [:index]
  resources :diversities, except: [:new]
  # get '/diversity_intro', to: 'diversities#intro'
  get '/diversity_assessment', to: 'diversities#new'

  ## D & I assessments (updated) ##
  resources :respondents, only: [:new, :create] do
    resources :responses
  end
  get '/diversity_intro', to: 'respondents#new'
end

app/models/diversity.rb
class Diversity < ApplicationRecord
  validates :diversityOneValue,:diversityTwoValue,:diversityThreeValue, :diversityFourValue, :diversityFiveValue,:diversitySixValue,:diversitySevenValue,:diversityEightValue, :diversityNineValue, :diversityTenValue,
  :employmentOneValue, :employmentTwoValue, :employmentThreeValue, :employmentFourValue, :employmentFiveValue, :employmentSixValue,:employmentSevenValue, :employmentEightValue, :employmentNineValue, :employmentTenValue, :employmentElevenValue, :employmentTwelveValue, :employmentThirteenValue, :employmentFourteenValue,
  :commOneValue, :commTwoValue, :commThreeValue, :commFourValue, :commFiveValue,
  :cultureOneValue, :cultureTwoValue, :cultureThreeValue, :cultureFourValue, :cultureFiveValue, :cultureSixValue,:cultureSevenValue, :cultureEightValue, :cultureNineValue, :cultureTenValue, :cultureElevenValue, :cultureTwelveValue, :cultureThirteenValue, :cultureFourteenValue,:cultureFifteenValue,
  :name, :email, presence: { message: "was left unanswered." }
end

app/controllers/diversities_controller.rb
class DiversitiesController < ApplicationController
  before_action :set_diversity, only: [:show, :edit, :update, :destroy]

  # GET /diversities
  # GET /diversities.json
  def index
    @diversities = Diversity.all
  end

  def intro
  end  

  # GET /diversities/1
  # GET /diversities/1.json
  def show
    @dandi = Diversity.find(params[:id])

    diverse = @dandi.diversityOneValue + @dandi.diversityTwoValue + @dandi.diversityThreeValue + @dandi.diversityFourValue + @dandi.diversityFiveValue + @dandi.diversitySixValue + @dandi.diversitySevenValue + @dandi.diversityEightValue +  @dandi.diversityNineValue + @dandi.diversityTenValue
    @diversityScore = diverse/10/5.to_f


    employee = @dandi.employmentOneValue + @dandi.employmentTwoValue + @dandi.employmentThreeValue + @dandi.employmentFourValue + @dandi.employmentFiveValue + @dandi.employmentSixValue + @dandi.employmentSevenValue + @dandi.employmentEightValue + @dandi.employmentNineValue + @dandi.employmentTenValue + @dandi.employmentElevenValue + @dandi.employmentTwelveValue + @dandi.employmentThirteenValue + @dandi.employmentFourteenValue
    @employmentScore = employee/14/5.to_f

    comm = @dandi.commOneValue + @dandi.commTwoValue + @dandi.commThreeValue + @dandi.commFourValue + @dandi.commFiveValue
    @commScore = comm/5/5.to_f

    culture = @dandi.cultureOneValue + @dandi.cultureTwoValue + @dandi.cultureThreeValue + @dandi.cultureFourValue + @dandi.cultureFiveValue + @dandi.cultureSixValue + @dandi.cultureSevenValue + @dandi.cultureEightValue + @dandi.cultureNineValue + @dandi.cultureTenValue + @dandi.cultureElevenValue + @dandi.cultureTwelveValue + @dandi.cultureThirteenValue + @dandi.cultureFourteenValue + @dandi.cultureFifteenValue
    @cultureScore = culture/15/5.to_f

  end

  # GET /diversities/new
  def new
    @questions = Question.all
    @answers = Answer.all
    @diversity = Diversity.new
  end

  # GET /diversities/1/edit
  def edit
  end

  # POST /diversities
  # POST /diversities.json
  def create
    @diversity = Diversity.new(diversity_params)

    respond_to do |format|
      if @diversity.save
        format.html { redirect_to @diversity, notice: 'Diversity was successfully created.' }
        format.json { render :show, status: :created, location: @diversity }
      else
        format.html { render :new }
        format.json { render json: @diversity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diversities/1
  # PATCH/PUT /diversities/1.json
  def update
    respond_to do |format|
      if @diversity.update(diversity_params)
        format.html { redirect_to @diversity, notice: 'Diversity was successfully updated.' }
        format.json { render :show, status: :ok, location: @diversity }
      else
        format.html { render :edit }
        format.json { render json: @diversity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diversities/1
  # DELETE /diversities/1.json
  def destroy
    @diversity.destroy
    respond_to do |format|
      format.html { redirect_to diversities_url, notice: 'Diversity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diversity
      @diversity = Diversity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diversity_params
      params.fetch(:diversity).permit(:diversityOneValue,:diversityTwoValue,:diversityThreeValue, :diversityFourValue, :diversityFiveValue,:diversitySixValue,:diversitySevenValue,:diversityEightValue, :diversityNineValue, :diversityTenValue,

      :employmentOneValue, :employmentTwoValue, :employmentThreeValue, :employmentFourValue, :employmentFiveValue, :employmentSixValue,:employmentSevenValue, :employmentEightValue, :employmentNineValue, :employmentTenValue, :employmentElevenValue, :employmentTwelveValue, :employmentThirteenValue, :employmentFourteenValue,
      :commOneValue, :commTwoValue, :commThreeValue, :commFourValue, :commFiveValue,
      :cultureOneValue, :cultureTwoValue, :cultureThreeValue, :cultureFourValue, :cultureFiveValue, :cultureSixValue,:cultureSevenValue, :cultureEightValue, :cultureNineValue, :cultureTenValue, :cultureElevenValue, :cultureTwelveValue, :cultureThirteenValue, :cultureFourteenValue,:cultureFifteenValue,
      :name, :email)
    end
end

app/helpers/diversities_helper.rb
module DiversitiesHelper
end

app/views/diversities/edit.html.erb
<h1>Editing Diversity</h1>

<%= render 'form', diversity: @diversity %>

<%= link_to 'Show', @diversity %> |
<%= link_to 'Back', diversities_path %>

app/views/diversities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diversities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diversities.each do |diversity| %>
      <tr>
        <td><%= link_to 'Show', diversity %></td>
        <td><%= link_to 'Edit', edit_diversity_path(diversity) %></td>
        <td><%= link_to 'Destroy', diversity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diversity', new_diversity_path %>

app/views/diversities/intro.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="diversity_intro">
        <h3>Diversity &amp; Inclusion Self Assessment</h3>
        <p>
          This tool enables organizations to benchmark their current diversity and inclusion activities and identify areas ripe for improvement and/or change.
        </p>
        <p>
          The higher the score, the better your company performs against key diversity and inclusion criteria and the more closely it aligns with industry best practices. If your company gets a lower score, there will be more work to do to bring you in line with diversity and inclusion best practices.
        </p>
        <p>
          Whatever your score, there is always room for improvement. The aim of this assessment is to provide practical guidance to guide and focus your efforts as your company continues to mature its approach to diversity and inclusion.
        </p>
        <a href="/diversity_assessment">
          <span>Begin assessment</span>
          <i class="fa fa-arrow-circle-o-right fa-3x" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/diversities/new.html.erb
<div class="hand_image"></div>
<%= render 'form', diversity: @diversity %>

app/views/diversities/show.html.erb
<div class="container">
  <div class="response-box1">
    <div class="container">
      <h2 class="well">Your Results</h2>
      <!-- Category 1 -->
      <div class="row">
        <div class="col-xs-4">
          <div class="categories-title">
            Commitment to Diversity
          </div>
        </div>
        <div class="col-xs-8">
          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @diversityScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@diversityScore * 100, precision: 0) %>;"> <%= number_to_percentage(@diversityScore * 100, precision: 0) %>
            </div>
          </div>
        </div>
      </div>
      <!-- Category 2 -->
      <div class="row">
        <div class="col-xs-4">
          <div class="categories-title">
            Employment Practices
          </div>
        </div>
        <div class="col-xs-8">
          <div class="progress">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @employmentScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@employmentScore * 100, precision: 0) %>;">

              <%= number_to_percentage(@employmentScore * 100, precision: 0) %>
            </div>
          </div>
        </div>
      </div>
      <!-- Category 3 -->
      <div class="row">
        <div class="col-xs-4">
          <div class="categories-title">
            Communication
          </div>
        </div>
        <div class="col-xs-8">
          <div class="progress">
            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<%= @commScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@commScore * 100, precision: 0) %>;">
              <%= number_to_percentage(@commScore * 100, precision: 0) %>
            </div>
          </div>
        </div>
      </div>
      <!-- Category 4 -->
      <div class="row">
        <div class="col-xs-4">
          <div class="categories-title">
            Culture
          </div>
        </div>
        <div class="col-xs-8">
          <div class="progress">
            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<%= @cultureScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@cultureScore * 100, precision: 0) %>;">
              <%= number_to_percentage(@cultureScore * 100, precision: 0) %>
            </div>
          </div>
        </div>
      </div>

      <hr>
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title"><strong>Commitment to Diversity</strong></h3>
          </div>
          <div class="panel-body">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>

        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><strong>Employment Practices</strong></h3>
          </div>
          <div class="panel-body">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title"><strong>Communication</strong></h3>
          </div>
          <div class="panel-body">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>


        <h4>Commitment to Diversity Section:</h4>

        <!-- Score and progress bar -->
        <div class="row">
          <div class="col-md-6">
            <p>Score</p>
            <div class="progress">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @diversityScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@diversityScore * 100, precision: 0) %>;"> <%= number_to_percentage(@diversityScore * 100, precision: 0) %>
              </div>
            </div>
          </div>
        </div>
        <% if @diversityScore >= 4 %>
        <h4>Looks like you are doing great in this area!</h4>
        <% elsif @diversityScore == 3%>
        <h4>You're doing okay but it is definitely an area you can improve on the links below will help!</h4>
        <% else @diversityScore < 3%>
        <h4>This is definitely an area you should work on, we would love to work with you on this area</h4>
        <% end %>

        <br>
        <h4>Employment Practices Section:</h4>
        <!-- Score and progress bar -->
        <div class="row">
          <div class="col-md-6">
            <p>Score</p>
            <div class="progress">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @employmentScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@employmentScore * 100, precision: 0) %>;">
                <%= number_to_percentage(@employmentScore * 100, precision: 0) %>
              </div>
            </div>
          </div>
        </div>
        <% if @employmentScore >= 4 %>
        <h4>Looks like you are doing great in this area!</h4>
        <% elsif @employmentScore == 3%>
        <h4>You're doing okay but it is definitely an area you can improve on the links below will help!</h4>
        <% else @employmentScore < 3%>
        <h4>This is definitely an area you should work on, we would love to work with you on this area</h4>
        <% end %>

        <br>
        <h4>Communication Section:</h4>
        <!-- Score and progress bar -->
        <div class="row">
          <div class="col-md-6">
            <p>Score</p>
            <div class="progress">
              <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<%= @commScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@commScore * 100, precision: 0) %>;">
                <%= number_to_percentage(@commScore * 100, precision: 0) %>
              </div>
            </div>
          </div>
        </div>
        <% if @commScore >= 4 %>
        <h4>Looks like you are doing great in this area!</h4>
        <% elsif @commScore == 3%>
        <h4>You're doing okay but it is definitely an area you can improve on the links below will help!</h4>
        <% else @commScore < 3%>
        <h4>This is definitely an area you should work on, we would love to work with you on this area</h4>
        <% end %>

        <br>
        <h4>Culture Section:</h4>
        <!-- Score and progress bar -->
        <div class="row">
          <div class="col-md-6">
            <p>Score</p>
            <div class="progress">
              <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<%= @cultureScore %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= number_to_percentage(@cultureScore * 100, precision: 0) %>;">
                <%= number_to_percentage(@cultureScore * 100, precision: 0) %>
              </div>
            </div>
          </div>
        </div>
        <% if @cultureScore >= 4 %>
        <h4>Looks like you are doing great in this area!</h4>
        <% elsif @cultureScore == 3%>
        <h4>You're doing okay but it is definitely an area you can improve on the links below will help!</h4>
        <% else @cultureScore < 3%>
        <h4>This is definitely an area you should work on, we would love to work with you on this area</h4>
        <% end %>
        <br>
    </div>
  </div>
</div>